-- AlterTable
ALTER TABLE `freightdocument` ADD COLUMN `expiryDate` DATETIME(3) NULL,
    ADD COLUMN `fileName` VARCHAR(191) NULL,
    ADD COLUMN `filePath` VARCHAR(191) NULL,
    ADD COLUMN `fileSize` INTEGER NULL,
    ADD COLUMN `issueDate` DATETIME(3) NULL,
    ADD COLUMN `issuedBy` VARCHAR(191) NULL,
    ADD COLUMN `mimeType` VARCHAR(191) NULL,
    ADD COLUMN `originalFileName` VARCHAR(191) NULL,
    ADD COLUMN `receivedFrom` VARCHAR(191) NULL,
    ADD COLUMN `referenceNo` VARCHAR(191) NULL,
    ADD COLUMN `rejectedAt` DATETIME(3) NULL,
    ADD COLUMN `rejectedById` VARCHAR(191) NULL,
    ADD COLUMN `rejectionReason` TEXT NULL,
    ADD COLUMN `remarks` TEXT NULL,
    ADD COLUMN `uploadedById` VARCHAR(191) NULL,
    ADD COLUMN `verifiedAt` DATETIME(3) NULL,
    ADD COLUMN `verifiedById` VARCHAR(191) NULL,
    MODIFY `type` ENUM('HBL', 'HAWB', 'MANIFEST', 'DEBIT_NOTE', 'SHIPPING_INSTRUCTION', 'ARRIVAL_NOTICE', 'MBL', 'MAWB', 'BOOKING_CONFIRMATION', 'DELIVERY_ORDER', 'CARRIER_INVOICE', 'VENDOR_DEBIT_NOTE', 'COMMERCIAL_INVOICE', 'PACKING_LIST', 'CERTIFICATE_OF_ORIGIN', 'MSDS_DG_CERTIFICATE', 'INSURANCE_CERTIFICATE', 'BILL_OF_ENTRY', 'EXPORT_DECLARATION', 'CUSTOMS_RELEASE', 'GATE_PASS', 'POD', 'DELIVERY_CHALLAN', 'WAREHOUSE_RECEIPT') NOT NULL,
    MODIFY `status` ENUM('DRAFT', 'UNDER_REVIEW', 'APPROVED', 'LOCKED', 'AMENDED', 'CANCELLED', 'PENDING_RECEIPT', 'RECEIVED', 'VERIFIED', 'REJECTED', 'EXPIRED', 'NOT_APPLICABLE') NOT NULL DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE `freightdocumentsequence` MODIFY `documentType` ENUM('HBL', 'HAWB', 'MANIFEST', 'DEBIT_NOTE', 'SHIPPING_INSTRUCTION', 'ARRIVAL_NOTICE', 'MBL', 'MAWB', 'BOOKING_CONFIRMATION', 'DELIVERY_ORDER', 'CARRIER_INVOICE', 'VENDOR_DEBIT_NOTE', 'COMMERCIAL_INVOICE', 'PACKING_LIST', 'CERTIFICATE_OF_ORIGIN', 'MSDS_DG_CERTIFICATE', 'INSURANCE_CERTIFICATE', 'BILL_OF_ENTRY', 'EXPORT_DECLARATION', 'CUSTOMS_RELEASE', 'GATE_PASS', 'POD', 'DELIVERY_CHALLAN', 'WAREHOUSE_RECEIPT') NOT NULL;

-- AddForeignKey
ALTER TABLE `FreightDocument` ADD CONSTRAINT `FreightDocument_uploadedById_fkey` FOREIGN KEY (`uploadedById`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `FreightDocument` ADD CONSTRAINT `FreightDocument_verifiedById_fkey` FOREIGN KEY (`verifiedById`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `FreightDocument` ADD CONSTRAINT `FreightDocument_rejectedById_fkey` FOREIGN KEY (`rejectedById`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
