import PDFDocument from "pdfkit/js/pdfkit.standalone.js";
import { blobGet } from "@/lib/blob/client";

export type PdfTable = {
  columns: Array<{ label: string; width: number; align?: "left" | "right" }>;
  rows: string[][];
};

export type PdfSection = {
  title: string;
  lines?: Array<[string, string]>;
  paragraphs?: string[];
  table?: PdfTable;
};

type PdfInput = {
  title: string;
  documentNo: string;
  companyName: string;
  companyDetails: string[];
  companyLogoPath?: string | null;
  status?: string;
  sections: PdfSection[];
  footer?: string;
};

function ensureSpace(doc: PDFKit.PDFDocument, height: number) {
  if (doc.y + height > doc.page.height - 65) doc.addPage();
}

function drawTable(doc: PDFKit.PDFDocument, table: PdfTable) {
  const startX = doc.page.margins.left;
  const padding = 5;
  const rowHeight = 24;
  ensureSpace(doc, rowHeight * 2);
  const headerY = doc.y;
  doc.rect(startX, headerY, table.columns.reduce((sum, column) => sum + column.width, 0), rowHeight).fill("#e2e8f0");
  let x = startX;
  table.columns.forEach((column) => {
    doc.fillColor("#0f172a").font("Helvetica-Bold").fontSize(8).text(column.label, x + padding, headerY + 8, { width: column.width - padding * 2, align: column.align });
    x += column.width;
  });
  doc.y = headerY + rowHeight;
  table.rows.forEach((row, rowIndex) => {
    ensureSpace(doc, rowHeight);
    const y = doc.y;
    if (rowIndex % 2) doc.rect(startX, y, table.columns.reduce((sum, column) => sum + column.width, 0), rowHeight).fill("#f8fafc");
    x = startX;
    table.columns.forEach((column, index) => {
      doc.fillColor("#334155").font("Helvetica").fontSize(8).text(row[index] ?? "-", x + padding, y + 7, { width: column.width - padding * 2, align: column.align, ellipsis: true });
      x += column.width;
    });
    doc.y = y + rowHeight;
  });
}

async function readSafeCompanyLogo(logoPath?: string | null) {
  if (!logoPath) return null;
  try {
    return await blobGet(logoPath);
  } catch {
    return null;
  }
}

export async function generatePdf(input: PdfInput) {
  const doc = new PDFDocument({ size: "A4", margins: { top: 48, right: 48, bottom: 55, left: 48 }, info: { Title: `${input.title} ${input.documentNo}` } });
  const chunks: Buffer[] = [];
  doc.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
  const completed = new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

  const logo = await readSafeCompanyLogo(input.companyLogoPath);
  const headerTop = doc.y;
  if (logo) {
    try {
      doc.image(logo, 48, headerTop, { fit: [110, 46], valign: "center" });
      doc.x = 170;
    } catch {
      doc.x = 48;
    }
  }
  doc.fillColor("#0f172a").font("Helvetica-Bold").fontSize(18).text(input.companyName, doc.x, headerTop, { width: logo ? 250 : 360 });
  doc.moveDown(0.25);
  doc.fillColor("#64748b").font("Helvetica").fontSize(8).text(input.companyDetails.filter(Boolean).join(" | "), { width: logo ? 250 : 360 });
  doc.x = 48;
  doc.y = Math.max(doc.y, headerTop + (logo ? 52 : 28));
  doc.moveDown(1.4);
  doc.fillColor("#0f172a").font("Helvetica-Bold").fontSize(22).text(input.title, { align: "right" });
  doc.fillColor("#334155").font("Helvetica").fontSize(10).text(input.documentNo, { align: "right" });
  if (input.status) doc.fillColor("#0f766e").font("Helvetica-Bold").text(input.status, { align: "right" });
  doc.moveDown(1);
  doc.strokeColor("#cbd5e1").moveTo(48, doc.y).lineTo(doc.page.width - 48, doc.y).stroke();
  doc.moveDown(1);

  for (const section of input.sections) {
    ensureSpace(doc, 60);
    doc.fillColor("#0f172a").font("Helvetica-Bold").fontSize(11).text(section.title);
    doc.moveDown(0.5);
    if (section.lines) {
      section.lines.forEach(([label, value]) => {
        ensureSpace(doc, 18);
        const y = doc.y;
        doc.fillColor("#64748b").font("Helvetica-Bold").fontSize(8).text(label.toUpperCase(), 48, y, { width: 130 });
        doc.fillColor("#334155").font("Helvetica").fontSize(9).text(value || "-", 178, y, { width: 365 });
        doc.y = Math.max(doc.y, y + 15);
      });
    }
    section.paragraphs?.filter(Boolean).forEach((paragraph) => {
      ensureSpace(doc, 35);
      doc.fillColor("#334155").font("Helvetica").fontSize(9).text(paragraph, { lineGap: 2 });
      doc.moveDown(0.5);
    });
    if (section.table) drawTable(doc, section.table);
    doc.moveDown(1);
  }

  doc.fillColor("#64748b").font("Helvetica").fontSize(8).text(input.footer ?? "Generated by Freito / CodeMoly", 48, doc.page.height - 38, { width: doc.page.width - 96, align: "center" });
  doc.end();
  return completed;
}
