-- AlterTable
ALTER TABLE `cargoreleasechecklist` ADD COLUMN `consigneeContact` VARCHAR(191) NULL,
    ADD COLUMN `deliveredBy` VARCHAR(191) NULL,
    ADD COLUMN `deliveryAddress` TEXT NULL,
    ADD COLUMN `deliveryDateTime` DATETIME(3) NULL,
    ADD COLUMN `deliveryLocation` VARCHAR(191) NULL,
    ADD COLUMN `deliveryOrderNo` VARCHAR(191) NULL,
    ADD COLUMN `deliveryRemarks` TEXT NULL,
    ADD COLUMN `driverName` VARCHAR(191) NULL,
    ADD COLUMN `driverPhone` VARCHAR(191) NULL,
    ADD COLUMN `exceptionReason` TEXT NULL,
    ADD COLUMN `gatePassNo` VARCHAR(191) NULL,
    ADD COLUMN `podReferenceNo` VARCHAR(191) NULL,
    ADD COLUMN `releaseDate` DATETIME(3) NULL,
    ADD COLUMN `transportVendorId` VARCHAR(191) NULL,
    ADD COLUMN `truckVehicleNo` VARCHAR(191) NULL,
    ADD COLUMN `verifiedAt` DATETIME(3) NULL,
    ADD COLUMN `verifiedBy` VARCHAR(191) NULL,
    ADD COLUMN `warehouseName` VARCHAR(191) NULL;
