// Single source of truth for a company's default roles and what each one
// grants. Used by prisma/seed.ts (one-time full-database seed) AND by
// lib/actions/platform.ts (provisioning a brand-new company created live
// through Platform -> Companies) so the two never drift apart -- exactly
// the kind of duplication that caused the companySafePermissions gaps
// found during QA.

export const COMPANY_ROLE_CODES = [
  "COMPANY_ADMIN",
  "OPERATIONS_MANAGER",
  "DOCUMENTATION_OFFICER",
  "ACCOUNTS_OFFICER",
  "SALES_EXECUTIVE",
  "CLIENT_USER",
] as const;

export type CompanyRoleCode = (typeof COMPANY_ROLE_CODES)[number];

export const COMPANY_ROLE_NAMES: Record<CompanyRoleCode, string> = {
  COMPANY_ADMIN: "Company Admin / Owner",
  OPERATIONS_MANAGER: "Operations Manager",
  DOCUMENTATION_OFFICER: "Documentation Officer",
  ACCOUNTS_OFFICER: "Accounts Officer",
  SALES_EXECUTIVE: "Sales Executive",
  CLIENT_USER: "Client User",
};

export const companyPermissionDefinitions = [
  ["dashboard:view", "View dashboard"],
  ["companies:manage", "Manage companies"],
  ["branding:manage", "Manage company branding"],
  ["documentTemplates:manage", "Manage quotation/invoice document templates"],
  ["branches:view", "View company branches"],
  ["branches:manage", "Manage company branches and memberships"],
  ["branches:access_all", "Access data across all assigned company branches"],
  ["users:manage", "Manage users"],
  ["roles:manage", "Manage roles and permissions"],
  ["customers:manage", "Manage customers"],
  ["vendors:manage", "Manage vendors"],
  ["shipments:view", "View shipment jobs"],
  ["shipments:create", "Create shipment jobs"],
  ["shipments:update", "Update shipment jobs"],
  ["shipments:delete", "Delete shipment jobs"],
  ["shipments:status:update", "Update shipment status timeline"],
  ["shipments:containers:manage", "Manage shipment containers"],
  ["shipments:view_assigned", "View assigned shipments"],
  ["shipmentWorkflow:view", "View shipment operations workflow"],
  ["shipmentWorkflow:update", "Update shipment operations workflow"],
  ["shipmentWorkflow:assign", "Assign shipment workflow handlers"],
  ["shipmentWorkflow:delete", "Delete shipment workflow steps"],
  ["shipmentRequests:view", "View shipment requests"],
  ["shipmentRequests:create", "Create shipment requests"],
  ["shipmentRequests:update", "Update shipment requests"],
  ["shipmentRequests:delete", "Delete shipment requests"],
  ["shipmentRequests:quote", "Create quotations from shipment requests"],
  ["shipmentRequests:convert", "Convert accepted requests to shipments"],
  ["documents:view", "View shipment documents"],
  ["documents:upload", "Upload shipment documents"],
  ["documents:update", "Update shipment document remarks"],
  ["documents:delete", "Delete shipment documents"],
  ["documents:verify", "Verify or reject shipment documents"],
  ["documents:download", "Download shipment documents"],
  ["documents:manage", "Manage shipment documents"],
  ["quotations:view", "View quotations"],
  ["quotations:create", "Create quotations"],
  ["quotations:update", "Update quotations"],
  ["quotations:delete", "Delete quotations"],
  ["quotations:approve", "Approve quotation status"],
  ["quotations:convert", "Convert quotation to shipment"],
  ["costing:view", "View shipment costing"],
  ["costing:update", "Update shipment costing"],
  ["costing:delete", "Delete shipment costing"],
  ["invoices:view", "View customer invoices"],
  ["invoices:create", "Create customer invoices"],
  ["invoices:update", "Update customer invoices"],
  ["invoices:delete", "Delete customer invoices"],
  ["invoices:send", "Mark customer invoices as sent"],
  ["vendorBills:view", "View vendor bills"],
  ["vendorBills:create", "Create vendor bills"],
  ["vendorBills:update", "Update vendor bills"],
  ["vendorBills:delete", "Delete vendor bills"],
  ["vendorBills:approve", "Approve vendor bills pending an approval policy"],
  ["payments:view", "View payments"],
  ["payments:create", "Create payments"],
  ["payments:update", "Update payments"],
  ["payments:delete", "Delete payments"],
  ["payments:approve", "Approve payments pending an approval policy"],
  ["approvalPolicies:manage", "Configure vendor bill/payment approval policies"],
  ["receivables:view", "View receivables"],
  ["payables:view", "View payables"],
  ["ledgers:view", "View customer and vendor ledgers"],
  ["accounts:manage", "Manage invoices, bills, and payments"],
  ["sales:manage", "Manage leads and quotations"],
  ["reports:view", "View reports"],
  ["reports:financial", "View internal financial and profitability reports"],
  ["reports:operations", "View operational, sales, document, and workflow reports"],
  ["reports:export", "Export report data"],
  ["reports:accounting", "View Trial Balance, Profit & Loss, and Balance Sheet statements"],
  ["tasks:list", "List company tasks"],
  ["tasks:view", "View company tasks"],
  ["tasks:create", "Create company tasks"],
  ["tasks:edit", "Edit company tasks"],
  ["tasks:delete", "Delete company tasks"],
  ["tasks:comment", "Comment on company tasks"],
  ["tasks:assign", "Assign company tasks"],
  ["carrierQueries:list", "List carrier buying queries"],
  ["carrierQueries:view", "View carrier buying queries"],
  ["carrierQueries:create", "Create carrier buying queries"],
  ["carrierQueries:edit", "Edit carrier buying queries"],
  ["carrierQueries:delete", "Delete carrier buying queries"],
  ["carrierProposals:view", "View internal carrier proposals"],
  ["carrierProposals:manage", "Manage internal carrier proposals"],
  ["carrierProposals:select", "Select carrier proposals"],
  ["bookings:view", "View freight bookings"],
  ["bookings:manage", "Manage freight bookings"],
  ["shippingInstructions:view", "View shipping instructions"],
  ["shippingInstructions:manage", "Manage shipping instructions"],
  ["billOfLading:view", "View BL and AWB workflow"],
  ["billOfLading:manage", "Manage BL and AWB workflow"],
  ["billOfLading:lock", "Lock final BL and AWB"],
  ["preAlerts:view", "View shipment pre-alerts"],
  ["preAlerts:manage", "Manage shipment pre-alerts"],
  ["preAlerts:send", "Mark shipment pre-alerts sent"],
  ["releaseChecks:view", "View destination release checks"],
  ["releaseChecks:manage", "Manage destination release checks"],
  ["exports:print", "Print customer-safe business documents"],
  ["exports:pdf", "Download customer-safe business document PDFs"],
  ["exports:csv", "Export CSV data listings"],
  ["imports:csv", "Import customer/vendor data from CSV"],
  ["notifications:view", "View in-app notifications"],
  ["notifications:update", "Mark in-app notifications as read"],
  ["notifications:delete", "Delete in-app notifications"],
  ["notificationTemplates:view", "View notification templates"],
  ["notificationTemplates:manage", "Manage company notification templates"],
  ["notificationDeliveries:view", "View notification delivery outbox"],
  ["notificationDeliveries:manage", "Manage notification delivery outbox"],
  ["communicationAccounts:view", "View communication accounts"],
  ["communicationAccounts:manage", "Manage communication accounts"],
  ["communicationAccounts:connect", "Connect communication accounts"],
  ["communicationAccounts:test", "Test communication accounts"],
  ["communicationAccounts:send", "Manually send prepared notification deliveries"],
  ["share:view", "View customer-safe share actions"],
  ["share:create", "Create customer-safe share links and outbox records"],
  ["share:send", "Send customer-safe shares using connected accounts"],
  ["audit_logs:view", "View audit logs"],
  ["client_portal:view", "View client portal"],
  ["clientPortalAccounts:view", "View client portal accounts"],
  ["clientPortalAccounts:create", "Create client portal accounts"],
  ["clientPortalAccounts:update", "Update client portal accounts"],
  ["clientPortalAccounts:delete", "Delete client portal accounts"],
  ["clientPortalAccounts:resetPassword", "Reset client portal account passwords"],
  ["ai:use", "Use enabled AI-powered features"],
  ["ai:configure", "Configure company AI provider settings"],
] as const;

// Deliberately NOT part of companyPermissionDefinitions: this must never
// flow into companySafePermissionKeys (which every COMPANY_ADMIN role gets
// in full at seed/provisioning time) as a blanket grant to every tenant.
// It's granted directly onto specific roles below instead, and is excluded
// from lib/actions/roles.ts's companySafePermissions allowlist so a company
// admin can never grant or revoke it via the Roles UI afterwards -- only a
// platform-level/seed action can.
export const SEED_ONLY_COMPANY_PERMISSION_DEFINITIONS = [
  ["companies:switch", "Switch to another company's data for cross-company audit reporting"],
] as const;

export const companySafePermissionKeys = companyPermissionDefinitions
  .map(([key]) => key)
  .filter((key) => key !== "companies:manage");

export const COMPANY_ROLE_PERMISSIONS: Record<CompanyRoleCode, string[]> = {
  COMPANY_ADMIN: [
    ...companySafePermissionKeys.filter((key) => key !== "shipments:view_assigned"),
    "companies:switch",
  ],
  OPERATIONS_MANAGER: [
    "dashboard:view",
    "customers:manage",
    "vendors:manage",
    "imports:csv",
    "shipments:view",
    "shipments:create",
    "shipments:update",
    "shipments:delete",
    "shipments:status:update",
    "shipments:containers:manage",
    "shipmentWorkflow:view",
    "shipmentWorkflow:update",
    "shipmentWorkflow:assign",
    "shipmentWorkflow:delete",
    "shipmentRequests:view",
    "shipmentRequests:create",
    "shipmentRequests:update",
    "shipmentRequests:delete",
    "shipmentRequests:quote",
    "shipmentRequests:convert",
    "documents:view",
    "documents:upload",
    "documents:update",
    "documents:delete",
    "documents:verify",
    "documents:download",
    "documents:manage",
    "quotations:view",
    "quotations:create",
    "quotations:update",
    "costing:view",
    "costing:update",
    "invoices:view",
    "vendorBills:view",
    "payments:view",
    "receivables:view",
    "payables:view",
    "reports:view",
    "reports:operations",
    "companies:switch",
    "tasks:list",
    "tasks:view",
    "tasks:create",
    "tasks:edit",
    "tasks:delete",
    "tasks:comment",
    "tasks:assign",
    "carrierQueries:list", "carrierQueries:view", "carrierQueries:create", "carrierQueries:edit", "carrierQueries:delete",
    "carrierProposals:view", "carrierProposals:manage", "carrierProposals:select",
    "bookings:view", "bookings:manage",
    "shippingInstructions:view", "shippingInstructions:manage",
    "billOfLading:view", "billOfLading:manage", "billOfLading:lock",
    "preAlerts:view", "preAlerts:manage", "preAlerts:send",
    "releaseChecks:view", "releaseChecks:manage",
    "exports:print",
    "exports:pdf",
    "exports:csv",
    "notifications:view",
    "notifications:update",
    "notificationTemplates:view",
    "notificationDeliveries:view",
    "communicationAccounts:view",
    "communicationAccounts:connect",
    "communicationAccounts:test",
    "communicationAccounts:send",
    "share:view",
    "share:create",
    "share:send",
    "clientPortalAccounts:view",
    "clientPortalAccounts:create",
    "clientPortalAccounts:update",
    "ai:use",
  ],
  DOCUMENTATION_OFFICER: [
    "dashboard:view",
    "shipments:view",
    "shipments:update",
    "shipments:status:update",
    "shipmentWorkflow:view",
    "shipmentWorkflow:update",
    "shipmentRequests:view",
    "shipmentRequests:update",
    "documents:view",
    "documents:upload",
    "documents:update",
    "documents:delete",
    "documents:verify",
    "documents:download",
    "documents:manage",
    "quotations:view",
    "costing:view",
    "invoices:view",
    "vendorBills:view",
    "reports:view",
    "reports:operations",
    "tasks:list",
    "tasks:view",
    "tasks:create",
    "tasks:edit",
    "tasks:comment",
    "tasks:assign",
    "shippingInstructions:view", "shippingInstructions:manage",
    "billOfLading:view", "billOfLading:manage",
    "preAlerts:view", "preAlerts:manage", "preAlerts:send",
    "bookings:view", "releaseChecks:view",
    "exports:print",
    "exports:pdf",
    "exports:csv",
    "notifications:view",
    "notifications:update",
    "notificationTemplates:view",
    "notificationDeliveries:view",
    "communicationAccounts:view",
    "communicationAccounts:send",
    "share:view",
    "share:create",
    "share:send",
    "clientPortalAccounts:view",
    "ai:use",
  ],
  ACCOUNTS_OFFICER: [
    "dashboard:view",
    "shipments:view",
    "shipmentWorkflow:view",
    "shipmentRequests:view",
    "documents:view",
    "documents:download",
    "quotations:view",
    "costing:view",
    "costing:update",
    "invoices:view",
    "invoices:create",
    "invoices:update",
    "invoices:delete",
    "invoices:send",
    "vendorBills:view",
    "vendorBills:create",
    "vendorBills:update",
    "vendorBills:delete",
    "payments:view",
    "payments:create",
    "payments:update",
    "payments:delete",
    "receivables:view",
    "payables:view",
    "ledgers:view",
    "accounts:manage",
    "reports:view",
    "reports:financial",
    "reports:accounting",
    "tasks:list",
    "tasks:view",
    "tasks:create",
    "tasks:edit",
    "tasks:comment",
    "bookings:view",
    "releaseChecks:view", "releaseChecks:manage",
    "exports:print",
    "exports:pdf",
    "exports:csv",
    "notifications:view",
    "notifications:update",
    "notificationTemplates:view",
    "notificationDeliveries:view",
    "communicationAccounts:view",
    "communicationAccounts:send",
    "share:view",
    "share:create",
    "share:send",
    "clientPortalAccounts:view",
    "ai:use",
  ],
  SALES_EXECUTIVE: [
    "dashboard:view",
    "customers:manage",
    "imports:csv",
    "sales:manage",
    "shipments:view",
    "shipmentWorkflow:view",
    "shipmentRequests:view",
    "shipmentRequests:create",
    "shipmentRequests:update",
    "shipmentRequests:quote",
    "shipments:create",
    "documents:view",
    "documents:download",
    "quotations:view",
    "quotations:create",
    "quotations:update",
    "invoices:view",
    "receivables:view",
    "reports:view",
    "reports:operations",
    "tasks:list",
    "tasks:view",
    "tasks:create",
    "tasks:edit",
    "tasks:comment",
    "carrierQueries:list", "carrierQueries:view", "carrierQueries:create", "carrierQueries:edit",
    "carrierProposals:view",
    "bookings:view",
    "exports:print",
    "exports:pdf",
    "exports:csv",
    "notifications:view",
    "notifications:update",
    "notificationTemplates:view",
    "notificationDeliveries:view",
    "communicationAccounts:view",
    "communicationAccounts:send",
    "share:view",
    "share:create",
    "share:send",
    "clientPortalAccounts:view",
    "clientPortalAccounts:create",
    "ai:use",
  ],
  CLIENT_USER: ["client_portal:view", "shipments:view_assigned"],
};
