import { PrintToolbar } from "@/components/print/print-toolbar";
import Image from "next/image";

export function PrintLayout({
  title,
  documentNo,
  status,
  company,
  pdfUrl,
  logoUrl,
  children,
}: {
  title: string;
  documentNo: string;
  status?: string | null;
  company: { name: string; legalName?: string | null; address?: string | null; email?: string | null; phone?: string | null };
  pdfUrl?: string;
  logoUrl?: string | null;
  children: React.ReactNode;
}) {
  return (
    <main className="print-document mx-auto my-6 max-w-[210mm] bg-white p-8 text-slate-900 shadow-sm print:m-0 print:max-w-none print:p-0 print:shadow-none">
      <PrintToolbar pdfUrl={pdfUrl} />
      <header className="flex items-start justify-between gap-8 border-b-2 border-slate-900 pb-6">
        <div>
          {logoUrl ? <Image alt={`${company.name} logo`} className="mb-3 h-14 w-auto object-contain" height={56} src={logoUrl} unoptimized width={180} /> : null}
          <p className="text-xl font-bold">{company.legalName ?? company.name}</p>
          <p className="mt-1 max-w-md text-sm text-slate-600">{company.address}</p>
          <p className="text-sm text-slate-600">{[company.email, company.phone].filter(Boolean).join(" | ")}</p>
        </div>
        <div className="text-right">
          <h1 className="text-3xl font-bold tracking-tight">{title}</h1>
          <p className="mt-1 text-lg font-semibold">{documentNo}</p>
          {status ? <p className="mt-2 text-sm font-semibold uppercase text-teal-700">{status}</p> : null}
        </div>
      </header>
      <div className="space-y-8 py-7">{children}</div>
      <footer className="border-t pt-4 text-center text-xs text-slate-500">Generated by Freito / CodeMoly</footer>
    </main>
  );
}

export function PrintSection({ title, children }: { title: string; children: React.ReactNode }) {
  return <section className="break-inside-avoid"><h2 className="mb-3 border-b pb-2 text-sm font-bold uppercase tracking-wide">{title}</h2>{children}</section>;
}

export function PrintDetails({ items }: { items: Array<[string, React.ReactNode]> }) {
  return <dl className="grid gap-x-8 gap-y-3 text-sm sm:grid-cols-2">{items.map(([label, value]) => <div key={label}><dt className="text-xs font-semibold uppercase text-slate-500">{label}</dt><dd className="mt-1">{value || "-"}</dd></div>)}</dl>;
}

export function PrintTable({ headers, rows }: { headers: string[]; rows: React.ReactNode[][] }) {
  return <div className="overflow-hidden border"><table className="w-full border-collapse text-left text-sm"><thead className="bg-slate-100"><tr>{headers.map((header) => <th className="border-b px-3 py-2 font-semibold" key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, rowIndex) => <tr className="break-inside-avoid border-b last:border-0" key={rowIndex}>{row.map((cell, cellIndex) => <td className="px-3 py-2 align-top" key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div>;
}
