import Link from "next/link";
import { notFound } from "next/navigation";
import { requireModuleAccess } from "@/lib/access/company-access";
import {
  generatePreAlert, saveBillOfLading, saveBooking, saveReleaseChecklist,
  saveShippingInstruction, saveStuffingPlan,
} from "@/lib/actions/freight-operations";
import { prisma } from "@/lib/db/prisma";
import { hasPermission, requirePermission } from "@/lib/permissions/rbac";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const input = "w-full rounded-md border border-slate-300 px-3 py-2 text-sm";
const check = "flex items-center gap-2 text-sm";
const dt = (value?: Date | null) => value?.toISOString().slice(0, 10) ?? "";

function formatStatus(status: string) {
  return status
    .split("_")
    .map(word => word.charAt(0) + word.slice(1).toLowerCase())
    .join(" ");
}

export default async function ShipmentOperationsPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await requirePermission("bookings:view");
  await requireModuleAccess(user.companyId!, "SHIPMENT_OPERATIONS");
  const { id } = await params;
  const shipment = await prisma.shipmentjob.findFirst({
    where: { id, companyId: user.companyId!, deletedAt: null },
    include: {
      customer: true, user_shipmentjob_assignedToIdTouser: true, shipmentrequest: true, container: { where: { deletedAt: null } },
      freightbooking: { include: { vendor: true } }, stuffingplan: true, shippinginstruction: true,
      billoflading: true, prealert: { include: { vendor: true } }, cargoreleasechecklist: true,
      carrierquery: { where: { deletedAt: null }, include: { vendor: true, carrierproposal: { where: { selected: true } } } },
      quotation_quotation_shipmentJobIdToshipmentjob: true, invoice: true, shipmentdocument: { where: { deletedAt: null } },
    },
  });
  if (!shipment) notFound();
  const vendors = await prisma.vendor.findMany({ where: { companyId: user.companyId!, deletedAt: null, status: "ACTIVE" }, orderBy: { name: "asc" } });
  const b = shipment.freightbooking, s = shipment.stuffingplan, si = shipment.shippinginstruction, bl = shipment.billoflading, pa = shipment.prealert, rc = shipment.cargoreleasechecklist;
  const timeline = [
    ["Customer Query Received", Boolean(shipment.shipmentrequest)],
    ["Carrier Query Sent", shipment.carrierquery.some(q => q.status !== "DRAFT")],
    ["Carrier Proposal Received", shipment.carrierquery.some(q => q.carrierproposal.length)],
    ["Customer Quotation Sent", shipment.quotation_quotation_shipmentJobIdToshipmentjob.some(q => q.status !== "DRAFT")],
    ["Quotation Accepted", shipment.quotation_quotation_shipmentJobIdToshipmentjob.some(q => q.status === "ACCEPTED")],
    ["Invoice Generated", shipment.invoice.length > 0],
    ["Booking Requested", Boolean(b?.bookingRequestAt)],
    ["Booking Acknowledged", Boolean(b?.acknowledgedAt)],
    ["Booking Confirmed", Boolean(b?.confirmedAt)],
    ["Container / Stuffing Planned", Boolean(s && s.status !== "NOT_PLANNED")],
    ["SI Submitted", si?.status === "SUBMITTED" || si?.status === "ACCEPTED"],
    ["Draft BL Received", Boolean(bl?.draftReceivedAt)],
    ["Draft BL Sent to Customer", Boolean(bl?.draftForwardedAt)],
    ["Draft BL Approved", Boolean(bl?.customerApprovalAt)],
    ["Final BL Locked", Boolean(bl?.finalLocked)],
    ["BL Release Confirmed", ["CONFIRMED", "RELEASED"].includes(bl?.releaseStatus ?? "")],
    ["Pre-alert Sent", Boolean(pa?.sentAt)],
    ["Shipment Arrived", Boolean(rc?.arrived)],
    ["Release Checks Completed", rc?.status === "READY_FOR_RELEASE"],
    ["Cargo Released", Boolean(rc?.cargoReleased)],
    ["Delivered", Boolean(rc?.delivered)],
  ] as const;
  return <main className="space-y-6 p-4 lg:p-6">
    <div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs uppercase text-slate-500">Phase 8I Operations</p><h1 className="text-2xl font-semibold">{shipment.jobNo}</h1><p className="text-sm text-slate-500">{shipment.customer.name} · {shipment.originCountry} → {shipment.destinationCountry}</p></div><div className="flex gap-2"><Button asChild variant="outline"><Link href={`/dashboard/shipments/${shipment.id}`}>Back to shipment</Link></Button><Button asChild variant="outline"><Link href={`/dashboard/carrier-queries/new?shipmentJobId=${shipment.id}`}>Create carrier query</Link></Button></div></div>

    <Card><CardHeader><CardTitle>Real operation timeline</CardTitle></CardHeader><CardContent className="grid gap-2 md:grid-cols-4">{timeline.map(([label, complete]) => <div key={label} className={`rounded-md border p-3 text-sm ${complete ? "border-emerald-200 bg-emerald-50" : "bg-slate-50"}`}><Badge variant={complete ? "success" : "secondary"}>{complete ? "Complete" : "Pending"}</Badge><p className="mt-2 font-medium">{label}</p></div>)}</CardContent></Card>

    <div className="grid gap-6 xl:grid-cols-2">
      <Card><CardHeader><CardTitle>Booking workflow</CardTitle></CardHeader><CardContent><form action={saveBooking} className="grid gap-3 md:grid-cols-2"><input type="hidden" name="shipmentJobId" value={shipment.id}/><label>Provider<select required name="vendorId" defaultValue={b?.vendorId ?? ""} className={input}><option value="">Select provider</option>{vendors.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Status<select name="status" defaultValue={b?.status ?? "BOOKING_REQUESTED"} className={input}>{["BOOKING_REQUESTED","BOOKING_ACKNOWLEDGED","BOOKING_CONFIRMED","FORWARDED_TO_CUSTOMER","AMENDED","CANCELLED"].map(x => <option key={x} value={x}>{formatStatus(x)}</option>)}</select></label><label>Provider reference<input name="providerReference" defaultValue={b?.providerReference ?? ""} className={input}/></label><label>Confirmation number<input name="confirmationNumber" defaultValue={b?.confirmationNumber ?? ""} className={input}/></label><label className="md:col-span-2">Notes<textarea name="notes" defaultValue={b?.notes ?? ""} className={input}/></label>{hasPermission(user,"bookings:manage") ? <Button type="submit">Save booking</Button> : null}</form><p className="mt-3 text-xs text-slate-500">Forwarding is manual status/share only; no email or WhatsApp is sent automatically.</p></CardContent></Card>

      <Card><CardHeader><CardTitle>Container / stuffing / depot plan</CardTitle></CardHeader><CardContent><form action={saveStuffingPlan} className="grid gap-3 md:grid-cols-2"><input type="hidden" name="shipmentJobId" value={shipment.id}/><label>Status<select name="status" defaultValue={s?.status ?? "NOT_PLANNED"} className={input}>{["NOT_PLANNED","PLANNED","CONTAINER_ASSIGNED","CARGO_RECEIVED","STUFFING_IN_PROGRESS","LOADED","COMPLETED"].map(x => <option key={x} value={x}>{formatStatus(x)}</option>)}</select></label><label>Depot / CFS / location<input name="depotLocation" defaultValue={s?.depotLocation ?? ""} className={input}/></label><label>Planned stuffing<input type="date" name="plannedStuffingAt" defaultValue={dt(s?.plannedStuffingAt)} className={input}/></label><label>Actual stuffing<input type="date" name="actualStuffingAt" defaultValue={dt(s?.actualStuffingAt)} className={input}/></label><label>Containers required<input type="number" name="containersRequired" defaultValue={s?.containersRequired ?? ""} className={input}/></label><label>Remarks<textarea name="remarks" defaultValue={s?.remarks ?? ""} className={input}/></label>{hasPermission(user,"bookings:manage") ? <Button type="submit">Save plan</Button> : null}</form></CardContent></Card>

      <Card><CardHeader><CardTitle>Shipping Instruction</CardTitle></CardHeader><CardContent><form action={saveShippingInstruction} className="grid gap-3 md:grid-cols-2"><input type="hidden" name="shipmentJobId" value={shipment.id}/><label>Status<select name="status" defaultValue={si?.status ?? "DRAFT"} className={input}>{["DRAFT","READY","SUBMITTED","ACCEPTED","REVISION_REQUIRED","CANCELLED"].map(x => <option key={x} value={x}>{formatStatus(x)}</option>)}</select></label><label>Booking reference<input name="bookingReference" defaultValue={si?.bookingReference ?? b?.confirmationNumber ?? ""} className={input}/></label><label>Shipper<input name="shipper" defaultValue={si?.shipper ?? shipment.shipperName ?? ""} className={input}/></label><label>Consignee<input name="consignee" defaultValue={si?.consignee ?? shipment.consigneeName ?? ""} className={input}/></label><label>Notify party<input name="notifyParty" defaultValue={si?.notifyParty ?? shipment.notifyParty ?? ""} className={input}/></label><label>Vessel/voyage/flight<input name="vesselVoyageFlight" defaultValue={si?.vesselVoyageFlight ?? ""} className={input}/></label><label>Port of loading<input name="portOfLoading" defaultValue={si?.portOfLoading ?? shipment.originPort ?? ""} className={input}/></label><label>Port of discharge<input name="portOfDischarge" defaultValue={si?.portOfDischarge ?? shipment.destinationPort ?? ""} className={input}/></label><label className="md:col-span-2">Cargo description<textarea name="cargoDescription" defaultValue={si?.cargoDescription ?? shipment.cargoDescription} className={input}/></label><label>HS code<input name="hsCode" defaultValue={si?.hsCode ?? shipment.hsCode ?? ""} className={input}/></label><label>Freight term<select name="freightTerm" defaultValue={si?.freightTerm ?? ""} className={input}><option value="">Select</option><option>PREPAID</option><option>COLLECT</option></select></label><label>Release preference<select name="releasePreference" defaultValue={si?.releasePreference ?? "NOT_APPLICABLE"} className={input}>{["ORIGINAL_BL","SURRENDER_BL","TELEX_RELEASE","SEAWAY_BILL","AWB_RELEASE","NOT_APPLICABLE"].map(x => <option key={x} value={x}>{formatStatus(x)}</option>)}</select></label><label>Special instructions<textarea name="specialInstructions" defaultValue={si?.specialInstructions ?? ""} className={input}/></label>{hasPermission(user,"shippingInstructions:manage") ? <Button type="submit">Save SI</Button> : null}<Button asChild type="button" variant="outline"><Link href={`/dashboard/shipments/${shipment.id}/operations/print?type=si`}>Print SI</Link></Button></form></CardContent></Card>

      <Card><CardHeader><CardTitle>Draft / Final BL or AWB</CardTitle></CardHeader><CardContent>{bl?.finalLocked ? <div className="mb-3 rounded-md border border-amber-300 bg-amber-50 p-3 text-sm">Final BL is locked. Critical fields are protected server-side.</div> : null}<form action={saveBillOfLading} className="grid gap-3 md:grid-cols-2"><input type="hidden" name="shipmentJobId" value={shipment.id}/><input type="hidden" name="shippingInstructionId" value={si?.id ?? ""}/><label>Document type<select name="documentType" defaultValue={bl?.documentType ?? "HBL"} className={input}>{["HBL","MBL","AWB","HAWB","CMR"].map(x => <option key={x}>{x}</option>)}</select></label><label>Approval status<select name="approvalStatus" defaultValue={bl?.approvalStatus ?? "NOT_RECEIVED"} className={input}>{["NOT_RECEIVED","DRAFT_RECEIVED","SENT_TO_CUSTOMER","CUSTOMER_REVIEWING","APPROVED_BY_CUSTOMER","CORRECTION_REQUESTED"].map(x => <option key={x} value={x}>{formatStatus(x)}</option>)}</select></label><label>Draft number<input disabled={bl?.finalLocked} name="draftNumber" defaultValue={bl?.draftNumber ?? ""} className={input}/></label><label>Draft received<input disabled={bl?.finalLocked} type="date" name="draftReceivedAt" defaultValue={dt(bl?.draftReceivedAt)} className={input}/></label><label>Draft forwarded<input disabled={bl?.finalLocked} type="date" name="draftForwardedAt" defaultValue={dt(bl?.draftForwardedAt)} className={input}/></label><label>Final number<input disabled={bl?.finalLocked} name="finalNumber" defaultValue={bl?.finalNumber ?? ""} className={input}/></label><label>Release type<select disabled={bl?.finalLocked} name="releaseType" defaultValue={bl?.releaseType ?? "NOT_APPLICABLE"} className={input}>{["ORIGINAL_BL","SURRENDER_BL","TELEX_RELEASE","SEAWAY_BILL","AWB_RELEASE","NOT_APPLICABLE"].map(x => <option key={x} value={x}>{formatStatus(x)}</option>)}</select></label><label>Release status<select name="releaseStatus" defaultValue={bl?.releaseStatus ?? "PENDING"} className={input}>{["PENDING","REQUESTED","CONFIRMED","RELEASED","HOLD","CANCELLED"].map(x => <option key={x} value={x}>{formatStatus(x)}</option>)}</select></label><label className={check}><input type="checkbox" name="paymentReceived" defaultChecked={bl?.paymentReceived}/>Customer/shipper payment confirmed</label>{hasPermission(user,"billOfLading:lock") && !bl?.finalLocked ? <label className={check}><input type="checkbox" name="finalLocked"/>Lock final BL/AWB</label> : null}<p className="md:col-span-2 text-xs text-amber-700">Surrender/Telex/Seaway may release cargo without original paper BL. Confirm shipper authority and payment before release.</p>{hasPermission(user,"billOfLading:manage") && !bl?.finalLocked ? <Button type="submit">Save BL workflow</Button> : null}<Button asChild type="button" variant="outline"><Link href={`/dashboard/shipments/${shipment.id}/operations/print?type=bl`}>Print BL summary</Link></Button></form></CardContent></Card>

      <Card><CardHeader><CardTitle>Destination-agent pre-alert</CardTitle></CardHeader><CardContent><form action={generatePreAlert} className="grid gap-3 md:grid-cols-2"><input type="hidden" name="shipmentJobId" value={shipment.id}/><label>Status<select name="status" defaultValue={pa?.status ?? "READY"} className={input}>{["DRAFT","READY","SENT","ACKNOWLEDGED","REVISION_REQUIRED","CANCELLED"].map(x => <option key={x} value={x}>{formatStatus(x)}</option>)}</select></label><label>Destination agent<select name="destinationAgentId" defaultValue={pa?.destinationAgentId ?? ""} className={input}><option value="">Select agent</option>{vendors.filter(v => ["OVERSEAS_AGENT","C_AND_F_AGENT","OTHER"].includes(v.type)).map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label className={check}><input type="checkbox" name="invoiceAvailable" defaultChecked={pa?.invoiceAvailable}/>Commercial invoice available</label><label className={check}><input type="checkbox" name="packingListAvailable" defaultChecked={pa?.packingListAvailable}/>Packing list available</label><label className="md:col-span-2">Document checklist<textarea name="attachedDocumentChecklist" defaultValue={pa?.attachedDocumentChecklist ?? shipment.shipmentdocument.map(d => `${d.documentName}: ${d.status}`).join("\n")} className={input}/></label><label>Charges instruction<textarea name="chargesInstruction" defaultValue={pa?.chargesInstruction ?? ""} className={input}/></label><label>Remarks<textarea name="remarks" defaultValue={pa?.remarks ?? ""} className={input}/></label>{hasPermission(user,"preAlerts:manage") ? <Button type="submit">Generate / update pre-alert</Button> : null}<Button asChild type="button" variant="outline"><Link href={`/dashboard/shipments/${shipment.id}/operations/print?type=pre-alert`}>Print Pre-alert</Link></Button></form></CardContent></Card>

      <Card><CardHeader><CardTitle>Destination release checklist</CardTitle></CardHeader><CardContent><form action={saveReleaseChecklist} className="grid gap-3 md:grid-cols-2"><input type="hidden" name="shipmentJobId" value={shipment.id}/><label>Status<select name="status" defaultValue={rc?.status ?? "NOT_ARRIVED"} className={input}>{["NOT_ARRIVED","ARRIVED","DOCUMENTS_PENDING","PAYMENT_PENDING","BL_AUTH_PENDING","READY_FOR_RELEASE","RELEASED","DELIVERED","ON_HOLD","CANCELLED"].map(x => <option key={x} value={x}>{formatStatus(x)}</option>)}</select></label><label>Hold reason<input name="holdReason" defaultValue={rc?.holdReason ?? ""} className={input}/></label>{[["arrived","Shipment arrived"],["arrivalNoticeReceived","Arrival notice received"],["consigneeDocumentsReceived","Consignee documents received"],["shipperPaymentConfirmed","Shipper payment confirmed"],["customerPaymentConfirmed","Customer payment confirmed"],["bankBlAuthenticityVerified","Bank/BL authenticity verified"],["originalBlReceived","Original BL received"],["telexSurrenderConfirmed","Telex/surrender confirmed"],["deliveryOrderReleased","Delivery order released"],["customsReady","Customs/clearance ready"]].map(([name,label]) => <label key={name} className={check}><input type="checkbox" name={name} defaultChecked={Boolean(rc?.[name as keyof typeof rc])}/>{label}</label>)}<p className="md:col-span-2 text-xs text-amber-700">Ready/released/delivered is blocked unless payment and the applicable original BL or telex/surrender authenticity checks are complete.</p>{hasPermission(user,"releaseChecks:manage") ? <Button type="submit">Save release checks</Button> : null}<Button asChild type="button" variant="outline"><Link href={`/dashboard/shipments/${shipment.id}/operations/print?type=release`}>Print checklist</Link></Button></form></CardContent></Card>
    </div>
  </main>;
}
