import "dotenv/config";
import { PrismaMariaDb } from "@prisma/adapter-mariadb";
import { PrismaClient } from "../lib/generated/prisma/client";

function createAdapter() {
  const databaseUrl = process.env.DATABASE_URL;
  if (!databaseUrl) throw new Error("DATABASE_URL is required.");
  const url = new URL(databaseUrl);
  return new PrismaMariaDb({
    host: url.hostname,
    port: url.port ? Number(url.port) : 3306,
    user: decodeURIComponent(url.username),
    password: decodeURIComponent(url.password),
    database: url.pathname.replace(/^\//, ""),
  });
}

const prisma = new PrismaClient({ adapter: createAdapter() });

async function main() {
  console.log("Seeding 14 realistic Bangladesh freight shipment jobs...");

  // Fetch the existing reference shipment to get company, customer, user IDs
  const refJob = await prisma.shipmentJob.findFirst({
    where: { jobNo: "SEA-IMP-2026-0145" },
    include: { customer: true, assignedTo: true },
  });

  if (!refJob) {
    throw new Error("Reference shipment SEA-IMP-2026-0145 not found. Please ensure it exists first.");
  }

  const companyId = refJob.companyId;
  const customerId = refJob.customerId;
  const assignedToId = refJob.assignedToId;
  const createdById = refJob.createdById;

  console.log(`Company: ${companyId}`);
  console.log(`Customer: ${customerId}`);
  console.log(`Assigned To: ${assignedToId}`);

  // 14 realistic Bangladesh freight shipment jobs
  // Mix of IMPORT/EXPORT, SEA/AIR/LAND, various routes
  const jobs = [
    // 1 - Sea Export to USA
    {
      jobNo: "SEA-EXP-2026-0201",
      shipmentType: "EXPORT" as const,
      transportMode: "SEA" as const,
      loadType: "FCL" as const,
      tradeTerm: "FOB" as const,
      serviceScope: "PORT_TO_PORT" as const,
      originCountry: "Bangladesh",
      originPort: "Chittagong (CTGR)",
      destinationCountry: "United States",
      destinationPort: "Los Angeles (USLAX)",
      shipperName: "Epyllion Group",
      consigneeName: "H&M Hennes & Mauritz LP",
      notifyParty: "H&M Hennes & Mauritz LP, 5000 Fenton Ave, El Monte, CA 91731",
      carrierName: "Maersk Bangladesh Ltd",
      shippingLineOrAirline: "Maersk Line",
      vesselName: "Maersk Emerald",
      voyageNo: "ME2601N",
      mblNo: "MEDUBD20140162",
      hblNo: "FTO-HBEXP-2026-0201",
      bookingNo: "BK-MAE-20264782",
      blOrAwbDate: new Date("2026-06-15"),
      etd: new Date("2026-06-18"),
      eta: new Date("2026-07-20"),
      currentStatus: "In Transit",
      cargoDescription: "Ready Made Garments (RMG) - Men's Woven Shirts, 100% Cotton",
      hsCode: "6205.20.00",
      packageCount: 2400,
      packageType: "CARTONS",
      grossWeight: 18600,
      netWeight: 17200,
      cbm: 68.50,
      containers: ["MSKU8432156", "MSKU8432157"],
    },
    // 2 - Air Import from Germany
    {
      jobNo: "AIR-IMP-2026-0101",
      shipmentType: "IMPORT" as const,
      transportMode: "AIR" as const,
      loadType: "LCL" as const,
      tradeTerm: "CIF" as const,
      serviceScope: "PORT_TO_DOOR" as const,
      originCountry: "Germany",
      originPort: "Frankfurt Airport (FRA)",
      destinationCountry: "Bangladesh",
      destinationPort: "Hazrat Shahjalal Intl Airport (DAC)",
      placeOfDelivery: "Tejgaon Industrial Area, Dhaka",
      shipperName: "Siemens AG - Export Division",
      consigneeName: "Summit Power Ltd",
      notifyParty: "Summit Power Ltd, Summit Centre, 18 Kawran Bazar, Dhaka",
      carrierName: "Biman Bangladesh Airlines Cargo",
      shippingLineOrAirline: "Biman Bangladesh Airlines",
      flightNo: "BG-704",
      mawbNo: "997-81234567",
      hawbNo: "FTO-HAWB-2026-0101",
      bookingNo: "BK-BGD-AIR-9012",
      blOrAwbDate: new Date("2026-06-25"),
      etd: new Date("2026-06-26"),
      eta: new Date("2026-06-27"),
      currentStatus: "Customs Clearance",
      cargoDescription: "Industrial Switchgear Components, Spare Parts for Power Plant",
      hsCode: "8537.10.00",
      packageCount: 18,
      packageType: "CRATES",
      grossWeight: 3240,
      netWeight: 2980,
      chargeableWeight: 3240,
      cbm: 12.80,
      containers: [],
    },
    // 3 - Sea Import from China (FCL)
    {
      jobNo: "SEA-IMP-2026-0202",
      shipmentType: "IMPORT" as const,
      transportMode: "SEA" as const,
      loadType: "FCL" as const,
      tradeTerm: "CNF" as const,
      serviceScope: "PORT_TO_DOOR" as const,
      originCountry: "China",
      originPort: "Ningbo (CNNGB)",
      destinationCountry: "Bangladesh",
      destinationPort: "Chittagong (CTGR)",
      placeOfDelivery: "Gazipur, Dhaka",
      shipperName: "Ningbo Sunrise Textile Co., Ltd.",
      consigneeName: "DBL Group",
      notifyParty: "DBL Group, 170 Bir Uttam Rafiqul Islam Ave, Dhaka 1213",
      carrierName: "Maersk Bangladesh Ltd",
      shippingLineOrAirline: "Maersk Line",
      vesselName: "MSC Beatrice",
      voyageNo: "MSC-2609E",
      mblNo: "MEDUCN820345",
      hblNo: "FTO-HBIMP-2026-0202",
      bookingNo: "BK-MSC-78234",
      blOrAwbDate: new Date("2026-06-20"),
      etd: new Date("2026-06-22"),
      eta: new Date("2026-07-12"),
      currentStatus: "Pre-alert Received",
      cargoDescription: "Woven Fabric (Grey Cloth) - Polyester Cotton Blend, for Garment Industry",
      hsCode: "5513.11.00",
      packageCount: 560,
      packageType: "ROLLS",
      grossWeight: 28400,
      netWeight: 27000,
      cbm: 89.20,
      containers: ["MSCU6781234", "MSCU6781235", "MSCU6781236"],
    },
    // 4 - Sea Export to UK
    {
      jobNo: "SEA-EXP-2026-0202",
      shipmentType: "EXPORT" as const,
      transportMode: "SEA" as const,
      loadType: "FCL" as const,
      tradeTerm: "FOB" as const,
      serviceScope: "DOOR_TO_PORT" as const,
      originCountry: "Bangladesh",
      originPort: "Chittagong (CTGR)",
      destinationCountry: "United Kingdom",
      destinationPort: "Felixstowe (GBFXT)",
      pickupAddress: "Palmal Group Factory, Ashulia, Savar, Dhaka 1341",
      shipperName: "Palmal Group",
      consigneeName: "Next Retail Ltd",
      notifyParty: "Next Retail Ltd, Desford Road, Enderby, Leicester LE19 4AT",
      carrierName: "Maersk Bangladesh Ltd",
      shippingLineOrAirline: "CMA CGM",
      vesselName: "CMA CGM Marco Polo",
      voyageNo: "CMA-FE4-26N",
      mblNo: "CMABDCTG0293841",
      hblNo: "FTO-HBEXP-2026-0202",
      bookingNo: "BK-CMA-550219",
      blOrAwbDate: new Date("2026-07-01"),
      etd: new Date("2026-07-05"),
      eta: new Date("2026-07-28"),
      currentStatus: "Vessel Loaded",
      cargoDescription: "Ladies Knitwear - Sweaters & Cardigans, Wool Blend",
      hsCode: "6110.20.00",
      packageCount: 3200,
      packageType: "CARTONS",
      grossWeight: 24800,
      netWeight: 22400,
      cbm: 82.00,
      containers: ["CMAU8291045", "CMAU8291046"],
    },
    // 5 - Sea Import from India (LCL)
    {
      jobNo: "SEA-IMP-2026-0203",
      shipmentType: "IMPORT" as const,
      transportMode: "SEA" as const,
      loadType: "LCL" as const,
      tradeTerm: "DAP" as const,
      serviceScope: "PORT_TO_DOOR" as const,
      originCountry: "India",
      originPort: "Kolkata (INCCU)",
      destinationCountry: "Bangladesh",
      destinationPort: "Chittagong (CTGR)",
      placeOfDelivery: "Tejgaon, Dhaka",
      shipperName: "Tata Steel Ltd",
      consigneeName: "BSRM Steels Ltd",
      notifyParty: "BSRM Steels Ltd, 57 Agrabad C/A, Chittagong 4100",
      carrierName: "Maersk Bangladesh Ltd",
      shippingLineOrAirline: "Shipping Corporation of India",
      vesselName: "SCI Vijayapura",
      voyageNo: "SCI-BD-2612",
      mblNo: "SCIBDCTG20198",
      hblNo: "FTO-HBIMP-2026-0203",
      bookingNo: "BK-SCI-BD-4412",
      blOrAwbDate: new Date("2026-07-02"),
      etd: new Date("2026-07-04"),
      eta: new Date("2026-07-10"),
      currentStatus: "Arrived",
      cargoDescription: "Cold Rolled Steel Coils for Construction Industry",
      hsCode: "7209.18.00",
      packageCount: 48,
      packageType: "COILS",
      grossWeight: 240000,
      netWeight: 238000,
      cbm: 180.00,
      containers: ["TEMU4521890"],
    },
    // 6 - Air Export to Japan
    {
      jobNo: "AIR-EXP-2026-0101",
      shipmentType: "EXPORT" as const,
      transportMode: "AIR" as const,
      loadType: "LCL" as const,
      tradeTerm: "FCA" as const,
      serviceScope: "DOOR_TO_PORT" as const,
      originCountry: "Bangladesh",
      originPort: "Hazrat Shahjalal Intl Airport (DAC)",
      destinationCountry: "Japan",
      destinationPort: "Narita Airport (NRT)",
      pickupAddress: "Square Group, Manikganj, Dhaka",
      shipperName: "Square Pharmaceuticals Ltd",
      consigneeName: "Sato Pharmaceutical Co., Ltd.",
      notifyParty: "Sato Pharmaceutical Co., Ltd., 5-2 Nishi-shinjuku, Shinjuku, Tokyo",
      carrierName: "Biman Bangladesh Airlines Cargo",
      shippingLineOrAirline: "Japan Airlines Cargo",
      flightNo: "JL-5041",
      mawbNo: "131-44287651",
      hawbNo: "FTO-HAWB-2026-0101A",
      bookingNo: "BK-JAL-23441",
      blOrAwbDate: new Date("2026-07-03"),
      etd: new Date("2026-07-04"),
      eta: new Date("2026-07-05"),
      currentStatus: "Delivered",
      cargoDescription: "Pharmaceutical Products - Generic Medicines, Temp-controlled",
      hsCode: "3004.90.00",
      packageCount: 96,
      packageType: "BOXES",
      grossWeight: 1240,
      netWeight: 1100,
      chargeableWeight: 1400,
      cbm: 4.20,
      containers: [],
    },
    // 7 - Sea Import from USA (FCL)
    {
      jobNo: "SEA-IMP-2026-0204",
      shipmentType: "IMPORT" as const,
      transportMode: "SEA" as const,
      loadType: "FCL" as const,
      tradeTerm: "CIF" as const,
      serviceScope: "PORT_TO_DOOR" as const,
      originCountry: "United States",
      originPort: "Houston (USHOU)",
      destinationCountry: "Bangladesh",
      destinationPort: "Chittagong (CTGR)",
      placeOfDelivery: "Narsingdi, Dhaka",
      shipperName: "Dow Chemical Co.",
      consigneeName: "Padma Oil Company Ltd",
      notifyParty: "Padma Oil Company Ltd, 24 Agrabad C/A, Chittagong",
      carrierName: "Maersk Bangladesh Ltd",
      shippingLineOrAirline: "Evergreen Line",
      vesselName: "Ever Liberal",
      voyageNo: "EL-UW2614",
      mblNo: "EGLV142600789231",
      hblNo: "FTO-HBIMP-2026-0204",
      bookingNo: "BK-EGL-23992",
      blOrAwbDate: new Date("2026-05-28"),
      etd: new Date("2026-06-01"),
      eta: new Date("2026-07-08"),
      actualArrival: new Date("2026-07-09"),
      currentStatus: "Closed",
      cargoDescription: "Chemical Raw Materials - PET Chips for Textile Industry",
      hsCode: "3907.60.00",
      packageCount: 800,
      packageType: "BAGS",
      grossWeight: 20000,
      netWeight: 20000,
      cbm: 40.00,
      containers: ["EGHU9123456", "EGHU9123457"],
    },
    // 8 - Sea Export to Netherlands
    {
      jobNo: "SEA-EXP-2026-0203",
      shipmentType: "EXPORT" as const,
      transportMode: "SEA" as const,
      loadType: "FCL" as const,
      tradeTerm: "FOB" as const,
      serviceScope: "PORT_TO_PORT" as const,
      originCountry: "Bangladesh",
      originPort: "Chittagong (CTGR)",
      destinationCountry: "Netherlands",
      destinationPort: "Rotterdam (NLRTM)",
      shipperName: "Ha-Meem Group",
      consigneeName: "G-Star Raw C.V.",
      notifyParty: "G-Star Raw C.V., Nachtwachtlaan 20, 1058 EX Amsterdam",
      carrierName: "Maersk Bangladesh Ltd",
      shippingLineOrAirline: "Hapag-Lloyd",
      vesselName: "Hamburg Express",
      voyageNo: "HL-FE26-012",
      mblNo: "HLCUBDCTG26070123",
      hblNo: "FTO-HBEXP-2026-0203",
      bookingNo: "BK-HLC-77823",
      blOrAwbDate: new Date("2026-07-04"),
      etd: new Date("2026-07-08"),
      eta: new Date("2026-08-02"),
      currentStatus: "Booking Confirmed",
      cargoDescription: "Denim Jeans - Men's & Women's, Various Washes",
      hsCode: "6203.42.00",
      packageCount: 2800,
      packageType: "CARTONS",
      grossWeight: 22400,
      netWeight: 20100,
      cbm: 75.60,
      containers: ["HLXU8901234", "HLXU8901235"],
    },
    // 9 - Air Import from Singapore
    {
      jobNo: "AIR-IMP-2026-0102",
      shipmentType: "IMPORT" as const,
      transportMode: "AIR" as const,
      loadType: "LCL" as const,
      tradeTerm: "DDP" as const,
      serviceScope: "DOOR_TO_DOOR" as const,
      originCountry: "Singapore",
      originPort: "Changi Airport (SIN)",
      destinationCountry: "Bangladesh",
      destinationPort: "Hazrat Shahjalal Intl Airport (DAC)",
      pickupAddress: "51 Bras Basah Road, Singapore 189554",
      placeOfDelivery: "Gulshan-2, Dhaka 1212",
      shipperName: "Flextronics Intl Singapore",
      consigneeName: "Grameenphone Ltd",
      notifyParty: "Grameenphone Ltd, GP House, Bashundhara, Dhaka 1229",
      carrierName: "Biman Bangladesh Airlines Cargo",
      shippingLineOrAirline: "Singapore Airlines Cargo",
      flightNo: "SQ-449",
      mawbNo: "618-91234567",
      hawbNo: "FTO-HAWB-2026-0102",
      bookingNo: "BK-SQC-88212",
      blOrAwbDate: new Date("2026-06-30"),
      etd: new Date("2026-07-01"),
      eta: new Date("2026-07-02"),
      currentStatus: "Delivered",
      cargoDescription: "4G/LTE Network Equipment - Base Station Controllers, Antennas",
      hsCode: "8517.62.00",
      packageCount: 24,
      packageType: "PALLETS",
      grossWeight: 1860,
      netWeight: 1650,
      chargeableWeight: 2100,
      cbm: 7.00,
      containers: [],
    },
    // 10 - Sea Import from South Korea
    {
      jobNo: "SEA-IMP-2026-0205",
      shipmentType: "IMPORT" as const,
      transportMode: "SEA" as const,
      loadType: "FCL" as const,
      tradeTerm: "CNF" as const,
      serviceScope: "PORT_TO_DOOR" as const,
      originCountry: "South Korea",
      originPort: "Busan (KRPUS)",
      destinationCountry: "Bangladesh",
      destinationPort: "Chittagong (CTGR)",
      placeOfDelivery: "BEZA Mirsarai Economic Zone, Chittagong",
      shipperName: "POSCO International Corp.",
      consigneeName: "PHP Family Group",
      notifyParty: "PHP Family Group, 256/A Agrabad C/A, Chittagong",
      carrierName: "Maersk Bangladesh Ltd",
      shippingLineOrAirline: "HMM (Hyundai Merchant Marine)",
      vesselName: "HMM Algeciras",
      voyageNo: "HMM-BD2608",
      mblNo: "HMMABDCTG0026841",
      hblNo: "FTO-HBIMP-2026-0205",
      bookingNo: "BK-HMM-33412",
      blOrAwbDate: new Date("2026-07-05"),
      etd: new Date("2026-07-08"),
      eta: new Date("2026-07-28"),
      currentStatus: "Vessel Loaded",
      cargoDescription: "Hot Rolled Steel Sheets for Shipbuilding Industry",
      hsCode: "7208.37.00",
      packageCount: 60,
      packageType: "BUNDLES",
      grossWeight: 600000,
      netWeight: 597000,
      cbm: 420.00,
      containers: ["HMMU8123456", "HMMU8123457", "HMMU8123458", "HMMU8123459"],
    },
    // 11 - Land Import from India
    {
      jobNo: "LND-IMP-2026-0101",
      shipmentType: "IMPORT" as const,
      transportMode: "LAND" as const,
      loadType: "FCL" as const,
      tradeTerm: "DAP" as const,
      serviceScope: "DOOR_TO_DOOR" as const,
      originCountry: "India",
      originPort: "Petrapole ICP, West Bengal",
      destinationCountry: "Bangladesh",
      destinationPort: "Benapole Land Port, Jessore",
      placeOfDelivery: "BEPZA Ishwardi EPZ, Pabna",
      shipperName: "Ramkrishna Forgings Ltd",
      consigneeName: "Bangladesh Steel Re-Rolling Mills (BSRM)",
      notifyParty: "BSRM Group, 57 Agrabad C/A, Chittagong",
      carrierName: "Truck Lagbe Corporate Logistics",
      shippingLineOrAirline: "N/A - Land Transport",
      mblNo: "LB-IMP-BNPOLE-20261101",
      hblNo: "FTO-LND-IMP-2026-0101",
      bookingNo: "BK-TLG-22781",
      blOrAwbDate: new Date("2026-07-06"),
      etd: new Date("2026-07-06"),
      eta: new Date("2026-07-08"),
      actualArrival: new Date("2026-07-08"),
      currentStatus: "Customs Clearance",
      cargoDescription: "Iron & Steel Scrap for Re-Rolling",
      hsCode: "7204.41.00",
      packageCount: 1,
      packageType: "LOOSE",
      grossWeight: 22000,
      netWeight: 22000,
      cbm: 50.00,
      containers: [],
    },
    // 12 - Sea Export to Canada
    {
      jobNo: "SEA-EXP-2026-0204",
      shipmentType: "EXPORT" as const,
      transportMode: "SEA" as const,
      loadType: "FCL" as const,
      tradeTerm: "FOB" as const,
      serviceScope: "PORT_TO_PORT" as const,
      originCountry: "Bangladesh",
      originPort: "Chittagong (CTGR)",
      destinationCountry: "Canada",
      destinationPort: "Vancouver (CAVAN)",
      shipperName: "Dekko Accessories Ltd",
      consigneeName: "Loblaw Companies Ltd",
      notifyParty: "Loblaw Companies Ltd, 1 President's Choice Circle, Brampton, ON",
      carrierName: "Maersk Bangladesh Ltd",
      shippingLineOrAirline: "Maersk Line",
      vesselName: "Maersk Madrid",
      voyageNo: "ME2614S",
      mblNo: "MEDUBD20260712",
      hblNo: "FTO-HBEXP-2026-0204",
      bookingNo: "BK-MAE-89923",
      blOrAwbDate: new Date("2026-07-07"),
      etd: new Date("2026-07-10"),
      eta: new Date("2026-08-18"),
      currentStatus: "Pre-alert Received",
      cargoDescription: "Jute & Jute Products - Shopping Bags, Floor Mats",
      hsCode: "6305.10.00",
      packageCount: 1800,
      packageType: "CARTONS",
      grossWeight: 19800,
      netWeight: 18200,
      cbm: 72.00,
      containers: ["MSKU9234567", "MSKU9234568"],
    },
    // 13 - Sea Import from Turkey
    {
      jobNo: "SEA-IMP-2026-0206",
      shipmentType: "IMPORT" as const,
      transportMode: "SEA" as const,
      loadType: "LCL" as const,
      tradeTerm: "CIF" as const,
      serviceScope: "PORT_TO_DOOR" as const,
      originCountry: "Turkey",
      originPort: "Mersin (TRMER)",
      destinationCountry: "Bangladesh",
      destinationPort: "Chittagong (CTGR)",
      placeOfDelivery: "Kanchpur, Narayanganj",
      shipperName: "Aksa Akrilik Kimya Sanayii A.S.",
      consigneeName: "Noman Group",
      notifyParty: "Noman Group, 68 Gulshan Avenue, Dhaka 1212",
      carrierName: "Maersk Bangladesh Ltd",
      shippingLineOrAirline: "MSC",
      vesselName: "MSC Katya",
      voyageNo: "MSC-AE026",
      mblNo: "MEDUMR820456",
      hblNo: "FTO-HBIMP-2026-0206",
      bookingNo: "BK-MSC-44512",
      blOrAwbDate: new Date("2026-06-12"),
      etd: new Date("2026-06-14"),
      eta: new Date("2026-07-18"),
      currentStatus: "In Transit",
      cargoDescription: "Acrylic Yarn for Knitwear Manufacturing",
      hsCode: "5511.10.00",
      packageCount: 280,
      packageType: "CONES",
      grossWeight: 14000,
      netWeight: 13600,
      cbm: 52.00,
      containers: ["MSDU7891234"],
    },
    // 14 - Air Import from Italy
    {
      jobNo: "AIR-IMP-2026-0103",
      shipmentType: "IMPORT" as const,
      transportMode: "AIR" as const,
      loadType: "LCL" as const,
      tradeTerm: "EXW" as const,
      serviceScope: "DOOR_TO_DOOR" as const,
      originCountry: "Italy",
      originPort: "Milan Malpensa Airport (MXP)",
      destinationCountry: "Bangladesh",
      destinationPort: "Hazrat Shahjalal Intl Airport (DAC)",
      pickupAddress: "Via delle Industrie 12, 20841 Carate Brianza, Italy",
      placeOfDelivery: "CEPZ, Chittagong",
      shipperName: "Biesse S.p.A.",
      consigneeName: "Partex Furniture Industries Ltd",
      notifyParty: "Partex Furniture, Partex Tower, 90 Kazi Nazrul Islam Ave, Dhaka",
      carrierName: "Biman Bangladesh Airlines Cargo",
      shippingLineOrAirline: "Emirates SkyCargo",
      flightNo: "EK-9743",
      mawbNo: "176-78321456",
      hawbNo: "FTO-HAWB-2026-0103",
      bookingNo: "BK-EKC-66112",
      blOrAwbDate: new Date("2026-07-07"),
      etd: new Date("2026-07-08"),
      eta: new Date("2026-07-09"),
      currentStatus: "In Transit",
      cargoDescription: "CNC Woodworking Machinery & Spare Parts",
      hsCode: "8465.91.00",
      packageCount: 8,
      packageType: "CASES",
      grossWeight: 4200,
      netWeight: 3900,
      chargeableWeight: 5000,
      cbm: 16.80,
      containers: [],
    },
  ];

  let created = 0;
  for (const job of jobs) {
    const { containers, ...jobData } = job;

    console.log(`Creating: ${jobData.jobNo} (${jobData.shipmentType} / ${jobData.transportMode})...`);

    // Skip if already exists
    const existing = await prisma.shipmentJob.findFirst({ where: { companyId, jobNo: jobData.jobNo } });
    if (existing) {
      console.log(`  → Skipped (already exists).`);
      created++;
      continue;
    }

    const newJob = await prisma.shipmentJob.create({
      data: {
        companyId,
        customerId,
        assignedToId,
        createdById,
        jobNo: jobData.jobNo,
        shipmentType: jobData.shipmentType,
        transportMode: jobData.transportMode,
        loadType: jobData.loadType,
        tradeTerm: jobData.tradeTerm,
        serviceScope: jobData.serviceScope,
        originCountry: jobData.originCountry,
        originPort: jobData.originPort,
        destinationCountry: jobData.destinationCountry,
        destinationPort: jobData.destinationPort,
        placeOfDelivery: jobData.placeOfDelivery,
        pickupAddress: jobData.pickupAddress,
        shipperName: jobData.shipperName,
        consigneeName: jobData.consigneeName,
        notifyParty: jobData.notifyParty,
        carrierName: jobData.carrierName,
        shippingLineOrAirline: jobData.shippingLineOrAirline,
        vesselName: (jobData as { vesselName?: string }).vesselName,
        voyageNo: (jobData as { voyageNo?: string }).voyageNo,
        flightNo: (jobData as { flightNo?: string }).flightNo,
        mblNo: jobData.mblNo,
        hblNo: jobData.hblNo,
        mawbNo: (jobData as { mawbNo?: string }).mawbNo,
        hawbNo: (jobData as { hawbNo?: string }).hawbNo,
        bookingNo: jobData.bookingNo,
        blOrAwbDate: jobData.blOrAwbDate,
        etd: jobData.etd,
        eta: jobData.eta,
        actualArrival: (jobData as { actualArrival?: Date }).actualArrival,
        currentStatus: jobData.currentStatus,
        cargoDescription: jobData.cargoDescription,
        hsCode: jobData.hsCode,
        packageCount: jobData.packageCount,
        packageType: jobData.packageType,
        grossWeight: jobData.grossWeight,
        netWeight: jobData.netWeight,
        chargeableWeight: (jobData as { chargeableWeight?: number }).chargeableWeight,
        cbm: jobData.cbm,
      },
    });

    // Create containers if any
    for (const containerNo of containers) {
      await prisma.container.create({
        data: {
          companyId,
          shipmentJobId: newJob.id,
          containerNo,
          containerType: "20GP",
          sealNo: `SL${Math.floor(Math.random() * 9000000 + 1000000)}`,
        },
      });
    }

    // Create initial status event
    await prisma.shipmentStatusEvent.create({
      data: {
        companyId,
        shipmentJobId: newJob.id,
        status: jobData.currentStatus,
        remarks: `Initial status set during job creation.`,
        updatedById: createdById,
      },
    });

    created++;
  }

  console.log(`\nDone! Created ${created} realistic shipment jobs.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
}).finally(async () => {
  await prisma.$disconnect();
});
